name: CI
on: push
jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Update theme
        # (Optional)If you have the theme added as submodule, you can pull it and use the most updated version
        run: git submodule update --init --recursive
      
      #- name: Read Hugo info
      #  id: hugo-info
      #  run: |
      #    . ./.HUGO_VERSION
      #    echo "::set-output name=HUGO_VERSION::${HUGO_VERSION}"
      #    echo "::set-output name=HUGO_EXTENDED::${HUGO_EXTENDED}"

      - name: Setup hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "latest" # '${{ steps.hugo-info.outputs.HUGO_VERSION }}'
          extended: true # ${{ steps.hugo-info.outputs.HUGO_EXTENDED }}

      - name: Build
        # remove --minify tag if you do not need it
        # docs: https://gohugo.io/hugo-pipes/minification/
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.TOKEN }}
          external_repository: coderqs/coderqs.github.io
          publish_dir: ./public
          #   keep_files: true
          user_name: coderqs
          user_email: <coderqs@coderqs.com>
          publish_branch: main
          #   cname: coderqs.com
